Hide direction if the address is empty
open-y-subprojects/openy_features pull request #20
Opened 2022-01-24 14:52 UTC by shuklina

PR https://github.com/ymcatwincities/yn/pull/5797
- [ ] Make sure that if there is no address for some branch, directions, and address are not displayed in the block. Path `/locations`

2022-01-24 15:12 UTC, podarok approved these changes

2022-01-24 15:19 UTC, podarok requested changes

2022-01-24 15:19 UTC, podarok commented on openy_location/modules/openy_loc_branch/config/optional/field.field.node.branch.field_location_address.yml
> +langcode: en
this config should go to original place https://github.com/open-y-subprojects/openy_features/blob/main/openy_location/modules/openy_loc_branch/config/install/field.field.node.branch.field_location_address.yml

2022-01-24 15:19 UTC, podarok commented on openy_location/modules/openy_loc_branch/config/optional/field.field.node.branch.field_location_directions.yml
> +langcode: en
this should be in original place https://github.com/open-y-subprojects/openy_features/blob/main/openy_location/modules/openy_loc_branch/config/install/field.field.node.branch.field_location_directions.yml

2022-01-25 11:54 UTC, podarok requested changes

2022-01-25 11:54 UTC, podarok commented on openy_location/modules/openy_loc_branch/config/install/field.field.node.branch.field_location_directions.yml
> +  default_config_hash: wECsSrrpKwpR9l0_0o0esc5NK7Rf-JTr46G-JOhFzEU
let's remove `_core` section completely

2022-01-25 12:00 UTC, merged

2022-01-31 16:13 UTC, shelleygoetz commented
Link to Jira ticket: https://openy.atlassian.net/browse/MAINTAIN-256