Ability to change the link text for "Directions" [YUOPENY-14]
open-y-subprojects/openy_features pull request #23
Opened 2022-10-07 12:55 UTC by andreyzb

Steps to test:

- [ ] Login as admin
- [ ] Edit any Location node
- [ ] Update `CONTACT INFO > DIRECTIONS > Link text` field value
- [ ] Verify on the front-end that Directions link text changed to new value

2022-10-20 10:14 UTC, andreyzb commented
@podarok please review

2022-10-20 10:41 UTC, podarok commented on openy_location/modules/openy_loc_camp/config/install/field.field.node.camp.field_location_directions.yml
> +default_value:
let's have hook_update_N for all these configs in order to support upgrade path

2022-10-20 10:41 UTC, podarok requested changes
needs upgrade path

2022-10-20 14:44 UTC, froboy commented on openy_location/modules/openy_loc_branch/config/install/field.field.node.branch.field_location_directions.yml
> +description: 'Directions link is auto generated from the Address field, however you can put here your own link. Otherwise please use <nolink> placeholder.'
```suggestion
description: 'Directions link is auto generated from the Address field, however you can put your own link here. For no link, enter: <nolink>.'
```

2022-10-20 14:44 UTC, froboy commented on openy_location/modules/openy_loc_camp/config/install/field.field.node.camp.field_location_directions.yml
> +description: 'Directions link is auto generated from the Address field, however you can put here your own link. Otherwise please use <nolink> placeholder.'
```suggestion
description: 'Directions link is auto generated from the Address field, however you can put your own link here. For no link, enter: <nolink>.'
```

2022-10-20 14:45 UTC, froboy commented on openy_location/modules/openy_loc_facility/config/install/field.field.node.facility.field_location_directions.yml
> +description: 'Directions link is auto generated from the Address field, however you can put here your own link. Otherwise please use <nolink> placeholder.'
```suggestion
description: 'Directions link is auto generated from the Address field, however you can put your own link here. For no link, enter: <nolink>.'
```

2022-10-21 07:53 UTC, merged

2022-10-21 07:53 UTC, podarok commented
@andreyzb if you rebase - no need to force push either - just simple merge and push

2022-11-07 20:15 UTC, froboy commented
This update failed for me when running on an existing install. The error was:

` [error]  Update aborted by: openy_loc_branch_update_8026, openy_loc_camp_update_8015, openy_loc_facility_update_8016 `

and each of those threw:

`>  [error]  The configuration property default_value.0.options.attributes.class.0 doesn't exist. `

It seems the cause is these default values:

```
default_value:
  -
    attributes: {  }
    uri: 'route:<nolink>'
    title: Directions
    options:
      attributes:
        class:
          - ''
```

Furthermore, setting a title for a link field will result in it always being populated unless the user deletes "Directions" which I don't think is desired. I would recommend using `placeholder`s instead of the default value here.

Finally, using `<nolink>` in a field description without escaping it results in empty text on the front end:

![Edit_Branch_TEst___Drush_Site-Install](https://user-images.githubusercontent.com/238201/200404907-551d1d31-02fe-4254-82c7-f4a26ef4113c.png)

To properly render `<nolink>` it needs to be escaped, like `&lt;nolink&gt;`, but since the `<nolink>` hint appears in the `URL` field description I think `For no link...` can be omitted on the `field_location_directions` description.

I will open a new PR with these fixes:
- remove `default_value` from Branch, Camp, Facility
- add placeholder for each
- fix description
- update hooks