Improvements for displaying Branch location holiday hours [YUOPENY-11]
open-y-subprojects/openy_features pull request #25
Opened 2022-10-17 12:27 UTC by andreyzb

To test use fresh OpenY setup with Demo content.

- [ ] Login as admin user
- [ ] Edit any Location
- [ ] Fill in few **Branch Holiday Hours** in the **Branch Hours** section and save. N.B. The Date field for the **Holiday Hours** item should be set to less then 2 weeks ahead and 24h behind current date to appear on the site (business logic).
- [ ] Verify **Holiday hours** appear in the `TODAY'S HOURS > View all hours` dropdown

2022-10-18 08:43 UTC, andreyzb commented
@podarok Please review

2022-10-20 12:04 UTC, podarok requested changes

2022-10-20 12:04 UTC, podarok commented on openy_location/modules/openy_loc_branch/config/install/core.entity_form_display.node.branch.default.yml
> +    - openy_field_holiday_hours
let's write hook_update_N for all these configs

2022-10-20 12:58 UTC, andreyzb commented
@podarok Updated hook added

2022-10-20 13:00 UTC, podarok requested changes

2022-10-20 13:00 UTC, podarok commented on openy_location/modules/openy_loc_branch/config/install/field.field.node.branch.field_branch_holiday_hours.yml
> +description: ''
Let's add description from your steps here?
![image](https://user-images.githubusercontent.com/563412/196955538-a393c0f4-3d4d-4c06-83d7-7715897969d9.png)
@andreyzb

2022-10-20 13:25 UTC, merged