feat: codesniffer and rector fixes for Drupal 10
open-y-subprojects/openy_features pull request #46
Opened 2023-05-03 12:47 UTC by podarok

Addresses: https://github.com/YCloudYUSA/yusaopeny/pull/8

2023-05-03 13:51 UTC, andreyzb commented on openy_prgf/modules/openy_prgf_event_listing/openy_prgf_event_listing.module
> + *
Empty docblock

2023-05-03 13:51 UTC, andreyzb commented on openy_prgf/modules/openy_prgf_class_sessions/src/Plugin/Block/ClassSessions.php
> +   *
Empty docblock

2023-05-03 13:51 UTC, andreyzb commented on openy_egym_iwatch/openy_egym_iwatch.install
> + *
Empty docblock

2023-05-03 13:51 UTC, andreyzb commented on openy_node/modules/openy_node_blog/src/BlogSimplePaginator.php
> + *
Empty docblock

2023-05-03 13:51 UTC, andreyzb commented on openy_node/modules/openy_node_social_post/openy_node_social_post.install
> + *
Empty docblock

2023-05-03 13:51 UTC, andreyzb commented on openy_node/src/BatchNodeUpdate.php
> + *
Empty docblock

2023-05-03 13:51 UTC, andreyzb commented on openy_prgf/modules/openy_prgf_embedded_groupexpro_schedule/openy_prgf_embedded_groupexpro_schedule.install
> +  ;
duplicated semicolon?

2023-05-03 13:51 UTC, andreyzb commented on openy_prgf/modules/openy_prgf_group_schedules/openy_prgf_group_schedules.install
> +  ;
Duplicate semicolon?

2023-06-28 19:48 UTC, froboy requested changes
@podarok I found one function missing an accessCheck that threw an error in D10. I can submit that separately, but it seems relevant in the context of these fixes. What else do we need to get them completed?

2023-06-28 19:48 UTC, froboy commented on openy_node/modules/openy_node_blog/src/BlogSimplePaginator.php
> +      ->range(0, 1)
This query needs an access check as per [this change record](https://www.drupal.org/node/3201242).
```suggestion
      ->range(0, 1)
      ->accessCheck(FALSE)
```

2023-06-28 19:49 UTC, froboy commented on openy_prgf/modules/openy_prgf_group_schedules/openy_prgf_group_schedules.install
> +  ;
```suggestion
```

2023-06-28 19:49 UTC, froboy commented on openy_prgf/modules/openy_prgf_embedded_groupexpro_schedule/openy_prgf_embedded_groupexpro_schedule.install
> +  ;
```suggestion
```

2023-06-28 19:53 UTC, froboy requested changes
Added suggestions to @andreyzb's comments.

2023-06-28 19:53 UTC, froboy commented on openy_node/src/BatchNodeUpdate.php
> + */
```suggestion
```

2023-06-28 19:53 UTC, froboy commented on openy_node/modules/openy_node_social_post/openy_node_social_post.install
> + */
```suggestion
```

2023-06-28 19:53 UTC, froboy commented on openy_egym_iwatch/openy_egym_iwatch.install
> + */
```suggestion
```

2023-06-28 19:53 UTC, froboy commented on openy_node/modules/openy_node_blog/src/BlogSimplePaginator.php
> + */
```suggestion
```

2023-06-28 19:53 UTC, froboy commented on openy_prgf/modules/openy_prgf_class_sessions/src/Plugin/Block/ClassSessions.php
> +   */
```suggestion
```

2023-06-28 19:53 UTC, froboy commented on openy_prgf/modules/openy_prgf_event_listing/openy_prgf_event_listing.module
> + */
```suggestion
```

2023-06-29 07:38 UTC, merged