Issue #80: Make field_amenities_icon optional.
open-y-subprojects/openy_features pull request #81
Opened 2024-03-08 20:47 UTC by carolpettirossi

2024-03-08 20:58 UTC, froboy commented
@carolpettirossi this is a great start, but in order to support our upgrade path we will need you to add an update hook that imports the new configuration. You can find an example of that [in the .install](https://github.com/open-y-subprojects/openy_features/blob/b84996de94fe8c3d4aa16fb8d4e1f6924c451339/openy_taxonomy/modules/openy_txnm_amenities/openy_txnm_amenities.install#L11-L26)

2024-04-30 17:42 UTC, froboy requested changes
@carolpettirossi please add this to `openy_txnm_amenities.install`

```
/**
 * Set amenities icon as not required.
 */
function openy_txnm_amenities_update_9001()
{
  $config_dir = \Drupal::service('extension.list.module')->getPath('openy_txnm_amenities') . '/config/install/';
  // Update multiple configurations.
  $configs = [
    'field.field.taxonomy_term.amenities.field_amenities_icon' => [
      'required',
    ],
  ];

  $config_updater = \Drupal::service('openy_upgrade_tool.param_updater');
  foreach ($configs as $config_name => $params) {
    $config = $config_dir . $config_name . '.yml';
    foreach ($params as $param) {
      $config_updater->update($config, $config_name, $param);
    }
  }
}
```

2024-05-07 16:05 UTC, carolpettirossi commented
@froboy , thanks for sending the code to me. I've just added it.

2024-05-28 07:19 UTC, podarok approved these changes

2024-05-28 07:19 UTC, merged